version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AppsyncTested"
s3_bucket = "aws-sam-deployments-251256923172"
s3_prefix = "AppsyncTested"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "APIName=\"AppsyncTested\""
