version: 0.2
phases:
    install:
        commands:
            - echo "Install phase"
    pre_build:
        commands:
            - echo "Pre-build phase"
            - cd ./code
    build:
        commands:
            - echo "Build phase"
    post_build:
        commands:
            - echo "Post-build phase"
            #- sam package --s3-bucket $BUILD_OUTPUT_BUCKET --template-file template.yml --output-template-file packaged.yml

artifacts:
    files:
        - code/packaged.yml
    discard-paths: yes
